TextEditor- assessment/Models/ErrorViewModel.cs
namespace TextEditor__assessment.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TextEditor- assessment/Models/file.cs
namespace TextEditor__assessment.Models
{
    public class file
    {
        public int id { get; set; }
        public string fileName { get; set; }
        public string text { get; set; }
    }
}

TextEditor- assessment/Controllers/FilesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace TextEditor__assessment.Controllers
{
    public class FilesController : Controller
    {
        IConfiguration configuration;
        public List<Models.file> fileNames = new List<Models.file>();
        public FilesController(IConfiguration _configuration)
        {
            this.configuration = _configuration;
        }
        public ActionResult AddText()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddText(IFormCollection collection)
        {
            try
            {
                Console.WriteLine(collection["text"]);
                Console.WriteLine("in add text post");
                SqlConnection connection = new SqlConnection(configuration.GetConnectionString("textdb"));
                connection.Open();

                string query = $"Insert into fileStorage values ('{collection["fileName"]}','{collection["text"]}')";
                SqlCommand command = new SqlCommand(query, connection);
                
                command.ExecuteNonQuery();
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                Console.Write(ex.Message);  
                return View();

            }
        }
        // GET: FilesController
        public ActionResult Index()
        {
            try
            {          
                Console.WriteLine("in index get");
                SqlConnection connection = new SqlConnection(configuration.GetConnectionString("textdb"));
                connection.Open();

                string query = $"SELECT * FROM filestorage";
                SqlCommand command = new SqlCommand(query, connection);

                SqlDataReader reader =  command.ExecuteReader();
                while (reader.Read())
                {
                    Models.file f = new Models.file();
                    f.id = reader.GetInt32(0);
                    f.fileName = reader.GetString(1);
                    fileNames.Add(f);


                    ViewBag.fileNames = fileNames;
                }
               // return RedirectToAction("Index");
                return View("Index");
            }
            catch (Exception ex)
            {
                Console.Write(ex.Message);
                return View();

            }
           

        }

        // GET: FilesController/Details/5
        public ActionResult View(int id)
        {
            try
            {
                Console.WriteLine("in index get"+id);
                SqlConnection connection = new SqlConnection(configuration.GetConnectionString("textdb"));
                connection.Open();

                string query = $"SELECT text FROM filestorage WHERE id = {id}";
                SqlCommand command = new SqlCommand(query, connection);
                ViewBag.text = command.ExecuteScalar();
                Console.WriteLine("text "+ViewBag.text);
                // return RedirectToAction("Index");
                return View();
            }
            catch (Exception ex)
            {
                Console.Write("Catch in view "+ex.Message);
                return View();

            }
            return View();
        }

        // GET: FilesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FilesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FilesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: FilesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FilesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FilesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

TextEditor- assessment/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TextEditor__assessment.Models;

namespace TextEditor__assessment.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TextEditor- assessment/Views/Files/AddText.cshtml
@{
    ViewData["Title"] = "AddText";
}

<h1>AddText</h1>

<form method="post">
    <input type="text" name="fileName"placeholder="enter the file name"/>
    <textarea name="text" rows="4" cols="50">

    </textarea>
    <button type="submit">Submit</button>
</form>

TextEditor- assessment/Views/Files/Index.cshtml
@model IEnumerable<TextEditor__assessment.Models.file>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                File Name
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in @ViewBag.fileNames) {
        <tr>
            <td>
                @item.fileName
            </td>
            <td>
                @Html.ActionLink("Open", "View", new {  id=item.id  }) |
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

TextEditor- assessment/Views/Files/View.cshtml
@model IEnumerable<TextEditor__assessment.Models.file>

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                file text
            </th>
        </tr>
    </thead>
    <tbody>

        <tr>
            <td>
                @ViewBag.text
            </td>
            @*<td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>*@
        </tr>

    </tbody>
</table>

TextEditor- assessment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TextEditor- assessment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TextEditor__assessment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TextEditor__assessment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TextEditor__assessment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Files" asp-action="AddText">Add Content</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TextEditor__assessment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>